	<div class="black_box_bg_middle"><div class="black_box_bg_top"><div class="black_box">
		<div class="content">
			<div class="title">
				<?php $schedule_title = lang('Terms And Conditions') ?>
				<span class="eutemia"><?php echo substr($schedule_title,0 , 1)?></span><span class="helvetica"><?php echo substr($schedule_title,1)?></span>
			</div>
			
			<div class="gray italic" style="padding: 10px; text-align: justify;">
				Last Updated: April 1, 2009
				<br/><br/>
				You must carefully read the terms and conditions of this website and Use agreement before You can use or view any of the public or private portions of the website accessible at VideoChat.com and other live and recorded content associated with VideoChat.com (the "Website"). You agree that further accessing or other use of the Website by You constitutes Your express affirmation that You agree to be bound by this Agreement.
				<br/><br/>
				1. PARTIES TO THIS AGREEMENT. The parties to this Use Agreement (the "Agreement") are You, the User, and VS Media, Inc. a California corporation (the "Company"), the licensor and/or owner of the Website. As used in this Agreement, the terms "we," and "us" are used interchangeably to refer to the Company and the Website; the term "You", "Your" and "User" are used to refer to you, the user of the Website.
				<br/><br/>
				1(a)Subject to Your acceptance of the terms and conditions set forth in this Agreement (as evidenced by Your submission login information and checking the Terms and Conditions checkbox on the login page) the Company agrees to provide to You access to the age restricted materials and age restricted areas of the Website for so long as You are in good standing.
				<br/><br/>
				1(b)You agree that this Agreement is subject to change by the Company at any time and changes shall become effective immediately upon notice to users by e-mail, posting, at or via hyperlink to the Website, or by mail. You should frequently check the "Terms and Conditions" link on the Website for changes. You acknowledge and agree that prior to Your agreement to these terms and conditions that You have had the opportunity to negotiate the terms of this Agreement and, if You have elected not to do so, You agree that the terms cannot be further modified, changed or edited unless You and the Company agree to do so in writing.
				<br/><br/>
				1(c)You agree that any action on Your part to bookmark to a page on the Website whereby any published warning page, any age verification page, and/or any other notice posted by the Company, including the page containing a link to the Website Terms and Conditions of use is located, is bypassed, such action shall constitute an implicit acceptance by You of all the Terms and Conditions set forth herein as well as an explicit acknowledgement or reaffirmation by You that You are an adult and at least 18 years of age or of the age of majority under the laws of Your state, province, or country.
				<br/><br/>
				2. SEXUALLY EXPLICIT MATERIAL. ALL MATERIALS, INCLUDING MESSAGES, AND OTHER COMMUNICATIONS, CONTAINED AT THE WEBSITE ARE INTENDED FOR DISTRIBUTION EXCLUSIVELY TO CONSENTING ADULTS IN LOCATIONS WHERE THE MATERIALS, MESSAGES AND OTHER COMMUNICATIONS CONTAINED AT THE WEBSITE DO NOT VIOLATE ANY COMMUNITY STANDARDS OR ANY FEDERAL, STATE, OR LOCAL LAWS OR REGULATIONS OF THE UNITED STATES OR ANY OTHER COUNTRY. NO PERSONS UNDER THE AGE OF EIGHTEEN (18) YEARS (TWENTY-ONE (21) IN PLACES WHERE EIGHTEEN YEARS IS NOT THE AGE OF MAJORITY) MAY DIRECTLY OR INDIRECTLY VIEW OR POSSESS ANY OF THE CONTENTS OF THE WEBSITE OR PLACE ANY ORDERS FOR ANY GOODS OR SERVICES ADVERTISED AT OR IN THE WEBSITE.
				<br/><br/>
				YOU HEREBY ACKNOWLEDGE AND REPRESENT THAT YOU KNOW AND UNDERSTAND THAT THE MATERIALS PRESENTED AT, AND/OR DOWNLOADABLE FROM, THE WEBSITE INCLUDE EXPLICIT VISUAL, AUDIO, AND/OR TEXTUAL DEPICTIONS OF NUDITY AND SEXUAL ACTIVITIES, INCLUDING WITHOUT LIMITATION, HETEROSEXUAL, BI-SEXUAL, AND HOMOSEXUAL ACTIVITIES OF AN EXPLICIT SEXUAL NATURE; THAT YOU ARE FAMILIAR WITH MATERIALS OF THIS KIND; THAT YOU ARE NOT OFFENDED BY SUCH MATERIALS; AND THAT BY AGREEING TO THESE TERMS AND CONDITIONS YOU ARE WARRANTING TO THE COMPANY THAT YOU ARE INTENTIONALLY AND KNOWINGLY SEEKING ACCESS TO SUCH EXPLICIT SEXUAL MATERIALS FOR YOUR OWN PERSONAL VIEWING.
				<br/><br/>
				3. AGE OF MAJORITY. NO PERSONS UNDER THE AGE OF EIGHTEEN (18) YEARS (TWENTY-ONE (21) IN JURISDICTIONS WHERE EIGHTEEN (18) YEARS IS NOT THE AGE OF MAJORITY) MAY DIRECTLY OR INDIRECTLY VIEW OR POSSESS ANY OF THE MATERIAL OR PLACE ANY ORDERS FOR ANY GOODS OR SERVICES ADVERTISED AT, IN OR THROUGH THE WEBSITE. YOU HEREBY FURTHER AFFIRM AND WARRANT THAT YOU ARE CURRENTLY OVER THE AGE OF EIGHTEEN (18) YEARS (TWENTY-ONE (21) IN PLACES WHERE EIGHTEEN (18) YEARS IS NOT THE AGE OF MAJORITY) AND ARE CAPABLE OF LAWFULLY ENTERING INTO AND EXECUTING THE TERMS OF THIS AGREEMENT.
				<br/><br/>
				4. GRANT OF LIMITED LICENSE. Subject to the terms and conditions set forth in this Agreement, the Company hereby grants You a limited, nonexclusive, and nontransferable license to use the Software and materials made available to You by and through this Website (hereafter "Materials") solely for Your personal non-commercial use, as provided by the Company during the period in which You are a user in good standing.
				<br/><br/>
				4(a)Acknowledgement of Company Property. You acknowledge and agree that all Materials contained at the Website are proprietary and constitute intellectual property owned by the Company or others who have licensed use of such Materials to the Company. You acknowledge and agree that as such You may access, view, download, receive, and otherwise use the Materials available at the Website only as specifically authorized by the Company and in accordance with the terms and conditions of use, only on one computer at a time and, if downloadable copies of the Materials are made available to You by the Website, You may make only a single copy of such Materials for Your own personal non-commercial use and enjoyment.
				<br/><br/>
				4(b)No Materials Sharing. You further acknowledge that the Company specifically prohibits You from doing any of the following acts, and You agree not to do any of these prohibited acts: (a) permitting other individuals to directly or indirectly use or view the Materials; (b) modifying, translating, reverse engineering, decompiling, disassembling the Materials (except to the extent applicable laws specifically prohibit such restriction); (c) making copies or creating derivative works based on the Materials, except as provided herein; (d) renting, leasing, or transferring any rights in the Materials; (e) removing any proprietary notices or labels on the Materials; and, (f) making any other use of the Materials not expressly permitted herein.
				<br/><br/>
				4(c)Expressly Authorized Use Only. You further represent and warrant to the Company that Your agreement to these terms and conditions constitutes an agreement that You shall not access, or attempt to access, any Materials available at the Website in a manner not expressly authorized by the Company. You agree and warrant that You shall at no time access, view, download, receive or otherwise use, or cause or enable others to access, view, download, receive or otherwise use Materials, directly or indirectly in places which the Company does not authorize such access, viewing, downloading, receipt or other use.
				<br/><br/>
				4(d)No Use In Prohibited Areas. You hereby acknowledge that You understand that the Company (and all persons affiliated therewith) does not authorize the accessing, viewing, downloading, duplication, receiving, transmission, broadcasting or other use of the Materials contained on the Website to or by any person, INCLUDING YOU, who is located in any of the areas designated as PROHIBITED AREAS.
				<br/><br/>
				4(e)Infringing Unauthorized Use. You further acknowledge that You understand and agree that any and all unauthorized access, viewing, downloading, receipt, duplication, or other use of Materials from the Website, in which You are directly or indirectly involved, including, but not limited to accessing, viewing, downloading, receiving or other use of Materials in PROHIBITED AREAS in any manner shall constitute intentional infringement(s) of the Company's and potentially others' intellectual property rights and other rights in such Materials and shall further constitute a violation of Company's trademark and other rights, including, but not limited to, rights of privacy.
				<br/><br/>
				4(f)You further acknowledge that You understand that any Materials, that You purchased and/or directly participated in, either in total or in part, such as but not limited to, private shows, may be seen by other users and/or employees of the Website. Any and all Materials from and/or appearing on the Website is the intellectual property of and solely owned by the Company and the Company reserves its right to use the Materials in any way it chooses in any medium at any time in perpetuity.
				<br/><br/>
				5. SOFTWARE LICENSE LIMITATION. WARNING: USE OF THIS SOFTWARE IS UNAUTHORIZED FOR PURPOSES THAT ARE ILLEGAL IN THE JURISDICTION WHICH THE SOFTWARE IS INSTALLED OR UNITED STATES LAW, WHICHEVER IS MORE RESTRICTIVE. USE OF THIS SOFTWARE FOR ILLEGAL PURPOSES CONSTITUTES AN IMMEDIATE BREACH OF THE USE PORTIONS OF THIS LICENSE. THE COMPANY RESERVES THE RIGHT TO IMMEDIATELY TERMINATE THE FUNCTIONALITY OF ANY OF ITS PRODUCTS IF SUCH ILLEGAL USE IS DETECTED OR REPORTED. BY USING THE PROVIDED SOFTWARE, YOU WAIVE ANY RIGHT TO REMEDIES THAT WOULD ORDINARILY RESULT FROM ANY TERMINATION OF FUNCTIONALITY BY THE COMPANY.
				<br/><br/>
				The Software Applet is provided by the Company to You for the sole purpose of allowing and facilitating Your use and enjoyment of the Website. The provided Software Applet is licensed, not sold, to You by Company for use only under the terms of this Agreement, and Company reserves any rights not expressly granted to You. You acknowledge and agree that the Company and its licensors and sub-licensors retain ownership of the Software Applet.
				<br/><br/>
				6. PROHIBITED AREAS OF ACCESS. All of the following areas constitute PROHIBITED AREAS from which no part of the Website may be accessed, viewed, downloaded or otherwise received. You are solely responsible for knowing if You are in such a Jurisdiction and if so, You must immediately terminate Your activities contemplated under this Agreement.
				<br/><br/>
				6(a)Prohibited Access Areas In The United States. All parts of the United States of America corresponding to the entire areas corresponding to United States Postal Service zip codes commencing with any of the following three digits:
				<br/><br/>
				PROHIBITED AREAS
				<br/><br/>
				Please click on the hyperlink above to access list of zip codes identified by their first three digits listing the prohibited areas in the United States from which You are not authorized to access or use Website or web site materials.
				<br/><br/>
				6(b)Other Prohibited Access Areas.
				<br/><br/>
				All parts of the following countries: Afghanistan, Germany, Kuwait, Iran, Iraq, Japan, Jordan, Libya, Pakistan, The Republic of China, Singapore, Saudi Arabia, Syria, The United Arab Emirates all areas subject to Sharia law Islamic law based on the Koran) Islamic law; and All parts of every other geophysical place corresponding to a political entity or part thereof in which the accessing, viewing, downloading or dissemination of, or other use of the materials contained in the Website would constitute a violation of any law, regulation, rule or custom.
				<br/><br/>
				7. OTHER IMPORTANT ACCESS AND USE RESTRICTIONS.
				<br/><br/>
				7(a)Use Subject To This Agreement. You acknowledge and agree that You may only access, view, download, receive materials available at, in or through the Website, including Content provided by any Website content providers ("Website Content Providers"), including third party content providers, only in accordance with these terms and conditions and other restrictions set forth in this Agreement and otherwise posted on the Website, including specific terms and condition associated with the acquisition of Website Content Provider's Content, and posted revisions of this Agreement.
				<br/><br/>
				7(b)No Commercial Use Of Website By You. You may access and use the Website only on one computer at a time and You may make only a single copy of the parts of the Website You access for Your own personal noncommercial educational and entertainment use and enjoyment. You may not use content for any commercial purpose whatsoever. You may not re-publish or provide any parts of the Website or any Website Content Providers' Content to any other person without express prior written authorization by the Company. Such prohibited uses include, without limitation, emailing, phone messaging or any other publication of the Website or Website Content Provider's Content, in whole or in part, on any web page, including on any personal web page You may own or be affiliated with, including any MySpace® page, regardless of whether any of the aforementioned uses are commercial or non-commercial. Any and all such unauthorized use will constitute intentional copyright infringement that could subject You to serious potential liability.
				<br/><br/>
				7(c)Password Security. You are responsible for providing all personal computer and communications equipment necessary to gain access to the Website. Access to and use of the Website is through the use of a password. You must keep Your password strictly confidential and You agree that if You share Your unique Login name and/or Your Password with another individual or entity that Your access to the Website is subject to immediate termination without notice or reimbursement of any kind and You are responsible for all fees incurred.
				<br/><br/>
				8. TERMINATION OF YOUR LICENSE TO USE WEBSITE. You acknowledge and agree that We may, in our sole discretion, terminate or suspend Your access to all or part of the Website at any time, with or without notice, for any reason, including, without limitation, breach of this Agreement. Without limiting the generality of the foregoing, any fraudulent, abusive, or otherwise illegal activity may be grounds for termination of Your access to all or part of the Website at Our sole discretion, and You may be referred to appropriate law enforcement agencies.
				<br/><br/>
				9. SERVICE MARKS (TRADEMARKS). Video Secrets® and VideoChat® and VS Media® are registered service marks of VS Media, Inc. No use of these marks by You or any other User shall be permitted except through the prior written authorization and permission of Company. All rights reserved.
				<br/><br/>
				10. YOU MAY NOT TRANSFER OR ASSIGN YOUR ACCESS RIGHTS OR OTHER PRIVILEGES; PASSWORDS. You shall not, under any circumstances, have the right to transfer or assign Your license to use the Website or any license(s) to use any Content You might obtain in, at, through or in association with, the Website, and You acknowledge that any attempted transfer or assignment of any such rights shall be void from the beginning. Any passwords that are issued for use at or in association with the Website or any Content provided by a Website Content Provider or affiliate are for Your individual use only. You will be responsible for the security of Your password(s). You must keep password(s) issued by the Company and/or Website affiliates strictly confidential, and You hereby agree to do so. If You use a password that the Company considers to be insecure, the Company shall be entitled to require the password to be changed and/or terminate Your authorized access to password protected areas. Any sharing of passwords or any other methods of unauthorized access to the Website with any other person is strictly forbidden. You agree that if You become involved in any violation of system security or if the Company or any Website affiliates reasonably so believes, the Company and all Website affiliates shall independently have the right to release details regarding such incidents and Your personal information to governmental agencies and system administrators at other sites in order to assist them in resolving security incidents, and to do so without any incurring any liability to You whatsoever.
				<br/><br/>				
				11. CODE OF CONDUCT. You agree, warrant and covenant to use the Website in accordance with the following Code of Conduct and that we may terminate Your right to use or access the Website and/or Content for violating any of these provisions:
				<br/><br/>
				11(a)No Illegal Use. You will not use the Website to engage in any form of illegal conduct, harassment or offensive behavior, including but not limited to the posting or uploading of communications or any graphic, video or audio content to the Website which contain libelous, slanderous, abusive or defamatory statements, or racist, obscene or offensive language.
				<br/><br/>
				11(b)No Infringing Use. You will not use the Website to infringe the privacy rights, property rights, including intellectual property rights, or any other rights of any person or entity, including, without limitation, the Company's rights, Website affiliate's rights or any other Website user's rights.
				<br/><br/>
				11(c)No Violation of Community Standards. You will not download or access any content available at or in association with the Website that does not comply with the community standards of the community to which You desire to have such content delivered or transmitted.
				<br/><br/>
				12. MEMBERSHIPS FEES; CANCELLATION. By accepting membership to Website and by accessing the content of Website You authorize the charges set forth below and agree to the following: a) Membership fees to Website are subject to change at any time at the sole and absolute discretion of Company. The official standard fee-for-service membership rates for the Website shall be set forth on the Website; b) All cancellations received by the Company are effective upon receipt; c) You hereby acknowledge and agree that if You cancel Your monthly membership, or if Your membership is cancelled by the Company, Your username and password will be removed from the system at the end of the then current monthly membership period and that You will be entitled to receive the full benefits of Your monthly membership until the end of such period. You agree that if You cancel at any time after purchasing fee-for-service credits from Website, You will still be charged the full processing fee. The Company may, at any time and at its sole discretion, cancel any membership; provided, however, that the Company shall refund all unused fee-for-service credit by automatic credit and waive the processing fee. You hereby authorize the Company to charge Your payment account (which You hereby acknowledge was entered by You into the sign-up page) to pay for Your fee-for-service fees to Website at the then current standard rate. You further authorize the Company to charge Your payment account for any and all purchases of products, services, and entertainment available through, at, in or on, or provided by, Website. You further agree to be personally liable for all charges incurred by You during or through the use of Website. Your liability for such charges shall continue after termination of Your membership The fee schedule for one-on-one and peep products is published at the Website. The pricing may change from time to time and it is Your responsibility to check this pricing to keep up-to-date.
				<br/><br/>
				13. NO TRANSFER OR ASSIGNMENT OF MEMBERSHIP. You agree that as a Member of the Website You shall not, under any circumstances, have the right to transfer or assign Your membership to any other person or entity, and that any attempted transfer or assignment of a membership shall be void. Your further agree that the Company, may at any time at its sole discretion and without prior notice to You, transfer or assign Your membership in the Website to an affiliated or non-affiliated Company.
				<br/><br/>
				14. PAYMENT AUTHORIZATION. Payment for the services provided to You at, and/or through Website may be made by automatic debit to Your payment account and You hereby authorize Company and its agents to transact such payments on Your behalf in the medium that is the normal course of business between You and the Company. Unless and until You notify Company that You wish to cancel or terminated Your Website membership, You hereby agree and authorize Company or its designated agent or assignee to use Your subscription information to Website for repurchase of fee-for-service credits as directed by You and to charge Your payment account to pay for such. You further authorize Company or its designated agent or assignee to charge Your payment account for any and all purchases of products, services, and entertainment provided to You by Website or for which You sign up.
				<br/><br/>
				You further agree that as a Member, You must promptly inform Company of any and all the following: loss or theft of the payment account used to pay for Membership to the Website or other goods or services obtained in, at, or through the Website; changes in the expiration date of the payment account; changes in home or billing address; apparent breaches of security regarding Your Membership, such as loss, theft, unauthorized disclosure or use of an ID or password; and all other changes pertaining to Your payment account used to pay for services pursuant to this Agreement which may affect Company's ability to expeditiously obtain payments due to Company. You agree that You will remain liable for any unauthorized use of Website or any of its services associated with Your Membership, until You have notified Company's Customer Service as to any of the aforementioned.
				<br/><br/>
				Please visit CommerceGate.com our authorized E-ticker, sales agent, and access manager provider. CommerceGate.com and 2000Charge.com are authorized billing agents for this website. By clicking "submit", you are also agreeing to be bound by their terms and conditions. Charges on your statement will appear as one of the following: VS3.COM, 2000CHARGE, or CGBILLING.
				<br/><br/>
				15. FRAUDULENT USE OF CARD. You hereby agree that as to any fraudulent reporting of a lost or stolen payment account used to obtain goods or services from Website or any fraudulent reporting of an unauthorized charge to Website on Your payment account which has been made by You or anyone under Your authority, at a time when a charge or other obligation for payment for goods and/or services to Website remains outstanding at the time of such fraudulent reporting, You shall be liable to the Company for liquidated damages of $30,000.00. The liability for liquidated damages specified in this Paragraph shall not limit any other liability You may have for breach of any other term, condition, promise, and/or warranty set forth in this Agreement. You further acknowledge and agree that You will remain liable to the Company for any unauthorized use of the Website associated with Your Membership.
				<br/><br/>
				16. TERMINATION OF MEMBERSHIP. Membership to the Website may be terminated at any time, with or without cause, by either Company or Member, subject to the cancellation policy and procedures set forth in this Agreement. Your liability for all charges incurred during Your Membership term shall continue after termination, for any reason, of Your membership.
				<br/><br/>
				17. AUTHORIZATION AND PERMISSION TO COMMUNICATE WITH YOU. Please read our PRIVACY POLICY. You hereby authorize, permit and request notices, advertisements, e-mail and other communications to be sent to You from the Company and from Website affiliates, Website Content Providers and/or their authorized agents, assigns, representatives, successors, affiliates and contractors. You acknowledge and agree that such communications may include any type of matter, including, without limitation, communications containing explicit nudity, explicit sexual depictions, sexual language and explicit sexual situations, including those involving heterosexuality, homosexuality and transsexuality. You agree that the Company shall not be under any obligation or restriction regarding the sale of Your email information to any third parties for any purpose. Moreover, You agree that Your request, authorization and permission to the Company send You such materials and communications herein shall continue to be in effect unless and until You notify the Company that You wish to be deleted from the Company's email list, in which case, You acknowledge and agree that the Company shall be obligated only to delete You from its email list and not the email list(s) of any third parties regardless of how such parties obtained Your email information through the Company. You acknowledge and agree that You will need to contact such third parties to be deleted from their email list(s). If You do not wish to receive advertising email from Company CLICK HERE.
				<br/><br/>
				17(a)Opt-out and Cancellation Provisions. At any time, You may opt out of future e-mailings and cancel Your receipt of e-mails from the Company by clicking the unsubscribe link at the bottom of the e-mail advertisement sent to You by the Company or by sending an e-mail cancellation request here.
				<br/><br/>
				17(b)Acknowledgment of Privacy Policy. You hereby acknowledge the Company's PRIVACY POLICY and waive any claims against the Company that arise out of in relation to any matter relating thereto.
				<br/><br/>
				17(c)No Actions Resulting From Registration In "No Contact" Registries. You hereby agree that You will not bring any action against Company, any Website Content Providers, or any of the Website's affiliates or any of any of the aforementioned parties' principals, employees or agents as a direct or indirect consequence of Your registration of an email address, mailing address, telephone number or other contact point with any governmental "do not email" registry with respect to any such contact point You have provided to the Company and/or one or more Website Content Providers after indicating that You have given the Company and/or such Website Content Providers permission to send You email, e.g., as You have done so in this Agreement above. You agree to indemnify the Company and Website Content Providers, the Website's affiliates and all their agents for any and all expenses and damages that result from any and all breaches of this subparagraph 14.3 and for any actions against Company, Website Affiliates, and/or any Website Content Providers that result from the Company and/or one or more Website Content Providers or affiliates sending You email that You have requested or authorized the Company, its affiliates and/or one or more Website Content Providers or affiliates to send You.
				<br/><br/>
				18. USE OF THE WEBSITE TO COMMUNICATE WITH OTHER USERS, WEBSITE AFFILIATES OR WEBSITE CONTENT PROVIDERS. The Company does not endorse, encourage, recommend or arrange personal or social communications or meetings among users of the Website or between a user and any individual Website affiliate or a user and any Website Content Provider. You are expected to use common sense and take appropriate measures and precautions to insure Your own personal safety and privacy in the event that You choose to communicate with, or meet with any person with whom You have communicated through the use of any public areas or chat areas of the Website, if any, or through materials provided by the Company, a Website affiliate or any Website Content Provider. You acknowledge and agree that Company shall not be held responsible in any way for the outcome of any contact or meeting, whether in person, by telephone or any other means, resulting from advertisements placed or responded to, or messages or communications sent or received by other Website users, Website affiliate, any Website Content Provider, or through any use, directly or indirectly, of the Website. You further acknowledge and agree that the Company does not screen any communications between Website affiliates or Content Providers and Website users and the Company has no control over such communications and makes no representations or warranties with respect to the character, veracity, age, health or any other attribute of any Website Content Providers, any affiliate or any other users of the Website, including any person who places any advertisements, profiles or notices on or in association with the Website.
				<br/><br/>
				18(a)No Inappropriate Communications By You. The Company may in its discretion provide a service that enables authorized Users to communicate with or otherwise share information with other Users or persons who offer to provide a service to Users, such as Website Content Providers, including performers, or to post information at, in or on the Website. If the Company provides such service and if You make use of the service, You agree that You will not post, submit, publish, display, disseminate, or otherwise communicate any defamatory, libelous, inaccurate, abusive, threatening, offensive, fraudulent, obscene, lewd, excessively violent, harassing or otherwise objectionable or illegal material or any material which would violate or infringe the copyright, trademark, rights of publicity, privacy rights or other rights of any person. You acknowledge that transmission of such material or any material that violates any federal, state, or local law in the United States or anywhere else in the world, is strictly prohibited by the Company and You further agree that any transmission of such material by You shall constitute a material breach of this Agreement entitling Company, without notice and without any liability for damages or reimbursement to You, to immediately terminate Your rights to access to the Website.
				<br/><br/>
				18(b)You Are Responsible For Any Inappropriate Communications. You acknowledge and agree that You, and not the Company, shall be solely responsible and liable for all damages, liability or other consequences, foreseen or unforeseen, of all information which You submit, publish, display, disseminate or otherwise communicate through the Website even if a claim for damages or liability should arise after termination of service.
				<br/><br/>
				18(c)No Confidential Communications; Communications In Chat Room Or Public Areas Not Private. You acknowledge and agree that all messages or content posted by You or others in any Chat rooms or public areas which may be provided on the Website shall be deemed to be readily accessible to the general public and consequently should not be considered private, confidential or proprietary. Consequently, You should not use the Website for any communication which You intend only You and the intended recipient(s) to read. Notice is hereby given that all messages entered into this Website can and may be read by the operators of the Website, whether or not they are the intended recipient(s). All messages and other communications by You shall not be deemed to be private or secure. You acknowledge that You have hereby been informed and noticed that any and all messages and other communications which You submit to Company or any other person in association with the use of the Website directly or through the Website can be read by the operators and/or other agents of Company whether or not they are the intended recipient(s).
				<br/><br/>
				18(d)Company Does Not Monitor Your Communications. Although we do not assume the duty or obligation to monitor any messages or other materials posted or uploaded to the Website by third parties, including You, we reserve the right but not the obligation, in our sole and absolute discretion, to monitor any and all materials posted or uploaded to the Website by third parties, including You, at any time without prior notice to ensure that they conform to any content guidelines or policies of the Website which may be applicable from time to time.
				<br/><br/>
				18(e)Company Reserves Right To Delete Your Communications. Although we do not assume the duty or obligation to monitor any messages, advertisements or other materials posted or uploaded to the Website by third parties, including You, and are not responsible for any content of these materials, we reserve the right, in our sole and absolute discretion, but are not obligated, to delete, move, or edit messages or materials, including without limitation advertisements and public postings, without notice, that we, in our sole discretion, deem to violate the Code of Conduct of the Website or any applicable content guidelines adopted from time to time by the Website, or to be otherwise unacceptable.
				<br/><br/>
				18(f)You Are Responsible For Any Content You Transmit. You acknowledge and agree that You shall remain solely responsible for the content of messages and other materials You may upload to the Website, to Website Content Providers or affiliates, or to other Users of the Website. You further acknowledge and agree that You shall remain solely responsible for any information You send, display, or receive through the Website even if a claim should arise relating thereto after termination of service.
				<br/><br/>
			</div>

			<div class="clear"></div>
		</div>
	</div>
	</div></div><div class="black_box_bg_bottom"></div>