<?php
define('SEPARATOR_SITE SETTINGS', 	'null');
define('SETTINGS_DEBUG', 	0);
define('EMAIL_ACTIVATION', 	1);
define('EMAIL_UNIQUE', 	0);
define('SUPPORT_EMAIL', 	'office@east-wolf.com');
define('SUPPORT_NAME', 	'east-wolf.com');
define('WEBSITE_NAME', 	'Your site name');
define('SETTINGS_DEFAULT_THEME', 	'modena_t3');
define('SETTINGS_SITE_TITLE', 	'thenaughtyandthenice.com');
define('SETTINGS_SITE_DESCRIPTION', 	'thenaughtyandthenice.com');
define('SETTINGS_SITE_KEYWORDS', 	'modena');
define('SEPARATOR_MEMCACHE SETTINGS', 	'null');
define('MEMCACHE_ENABLE', 	0);
define('MEMCACHE_HOST', 	'127.0.0.1');
define('MEMCACHE_PORT', 	11211);
define('SEPARATOR_CURRENCY SETTINGS', 	'null');
define('SETTINGS_CURRENCY_TYPE', 	0);
define('SETTINGS_REAL_CURRENCY_NAME', 	'USD');
define('SETTINGS_REAL_CURRENCY_SYMBOL', 	'$');
define('SETTINGS_VIRTUAL_CURRENCY_NAME', 	'chips');
define('SETTINGS_CENTS_PER_CREDIT', 	1);
define('SETTINGS_SHOWN_CURRENCY', 	'USD');
define('SEPARATOR_PRICE SETTINGS', 	'null');
define('WEBSITE_PERCENTAGE', 	50);
define('MIN_TRUE_PRIVATE_CHIPS_PRICE', 	10);
define('MAX_TRUE_PRIVATE_CHIPS_PRICE', 	100);
define('MIN_PRIVATE_CHIPS_PRICE', 	10);
define('MAX_PRIVATE_CHIPS_PRICE', 	100);
define('MIN_PEEK_CHIPS_PRICE', 	5);
define('MAX_PEEK_CHIPS_PRICE', 	100);
define('MIN_NUDE_CHIPS_PRICE', 	5);
define('MAX_NUDE_CHIPS_PRICE', 	100);
define('MIN_PAID_VIDEO_CHIPS_PRICE', 	5);
define('MAX_PAID_VIDEO_CHIPS_PRICE', 	100);
define('MIN_PHOTOS_CHIPS_PRICE', 	10);
define('MAX_PHOTOS_CHIPS_PRICE', 	100);
define('SEPARATOR_CHAT_SETTINGS', 	'null');
define('FREE_CHAT_LIMIT_NOTLOGGED', 	60);
define('FREE_CHAT_LIMIT_LOGGED_NO_CREDITS', 	120);
define('FREE_CHAT_LIMIT_LOGGED_WITH_CREDITS', 	9999);
define('MINIMUM_PAID_CHAT_TIME', 	60);
define('SEPARATOR_USER SETTINGS', 	'null');
define('BAN_EXPIRE_DATE', 	84000);
define('SEPARATOR_AFFILIATE SETTINGS', 	'null');
define('SETTINGS_TRANSACTION_PERCENTAGE', 	30);
define('SEPARATOR_FMS SETTINGS', 	'null');
define('FMS_SECRET_HASH', 	'MY_SECRET_HASH');
define('WEBSITE_LICENSE', 	'trial');
