<?php











						###############################################
						##                                           ##
						##            (!!)   WARNING   (!!)          ##
						##                                           ##
						##   THIS IS AN AUTOGENERATED FILE           ##
						##                                           ##
						##   DO NOT EDIT IT	                         ##
						##                                           ##
						###############################################





















		

define('SETTINGS_DEBUG', false);
define('EMAIL_ACTIVATION', true);
define('EMAIL_UNIQUE', false);
define('SUPPORT_EMAIL', 'office@east-wolf.com');
define('SUPPORT_NAME', 'east-wolf.com');
define('WEBSITE_NAME', 'TheNaughtyAndTheNice');
define('SETTINGS_DEFAULT_THEME', 'modena_t3');
define('SETTINGS_SITE_TITLE', 'thenaughtyandthenice.com');
define('SETTINGS_SITE_DESCRIPTION', 'thenaughtyandthenice.com');
define('SETTINGS_SITE_KEYWORDS', 'modena');
define('MEMCACHE_ENABLE', false);
define('MEMCACHE_HOST', '127.0.0.1');
define('MEMCACHE_PORT', '11211');
define('SETTINGS_CURRENCY_TYPE', '0');
define('SETTINGS_REAL_CURRENCY_NAME', 'USD');
define('SETTINGS_REAL_CURRENCY_SYMBOL', '$');
define('SETTINGS_VIRTUAL_CURRENCY_NAME', 'chips');
define('SETTINGS_CENTS_PER_CREDIT', '1');
define('SETTINGS_SHOWN_CURRENCY', 'USD');
define('WEBSITE_PERCENTAGE', '50');
define('MIN_TRUE_PRIVATE_CHIPS_PRICE', '10');
define('MAX_TRUE_PRIVATE_CHIPS_PRICE', '100');
define('MIN_PRIVATE_CHIPS_PRICE', '10');
define('MAX_PRIVATE_CHIPS_PRICE', '100');
define('MIN_PEEK_CHIPS_PRICE', '5');
define('MAX_PEEK_CHIPS_PRICE', '100');
define('MIN_NUDE_CHIPS_PRICE', '5');
define('MAX_NUDE_CHIPS_PRICE', '100');
define('MIN_PAID_VIDEO_CHIPS_PRICE', '5');
define('MAX_PAID_VIDEO_CHIPS_PRICE', '100');
define('MIN_PHOTOS_CHIPS_PRICE', '10');
define('MAX_PHOTOS_CHIPS_PRICE', '100');
define('FREE_CHAT_LIMIT_NOTLOGGED', '9999999');
define('FREE_CHAT_LIMIT_LOGGED_NO_CREDITS', '9999999');
define('FREE_CHAT_LIMIT_LOGGED_WITH_CREDITS', '9999999');
define('MINIMUM_PAID_CHAT_TIME', '60');
define('BAN_EXPIRE_DATE', '84000');
define('SETTINGS_TRANSACTION_PERCENTAGE', '30');
define('FMS_SECRET_HASH', 'vHDdpNyAz9xCnnzANAY8');
define('WEBSITE_LICENSE', 'trial');
